#! /usr/bin/env python
"""initsys helps you init your remote system.
The base script does the very simple stuff.
"""

import os
import sys

def copyKey(server, githubUser):
    """Execute from local for bootstrap... for now"""
    key = "https://github.com/" +githubUser +".keys"
    command = "ssh " +server 
    command += " '[ -d ~/.ssh ] || mkdir ~/.ssh; wget -O ~/.ssh/authorized_keys -N " +key +"; chmod -R 0700 ~/.ssh'"
    os.system(command)

def dlLocalAlias():
    myAliasFile = "https://raw.githubusercontent.com/Faeriol/initsys/master/bash_alias"
    os.system("wget -O .bash_alias -N " +myAliasFile)
    os.system("'[ -f ~/.bashrc ] && (grep -s -q \"source .bash_alias\" .bashrc || echo \"source .bash_alias\" >> ~/.bashrc)'")
    os.system("'[ -f ~/.profile ] && (grep -s -q \"source .bash_alias\" .profile || echo \"source .bash_alias\" >> ~/.profile)'")

def dlInitsys(server):
    myInitsys = "https://raw.githubusercontent.com/Faeriol/initsys/master/initsys"
    os.system("ssh " +server +" wget -O initsys -N " +myInitsys)

def dlLocalVimrc():
    myVimrc = "https://raw.githubusercontent.com/Faeriol/initsys/master/vimrc"
    os.system("wget -O .vimrc -N " +myVimrc)

def dlLocalScreenrc():
    myScreenrc = "https://raw.githubusercontent.com/Faeriol/initsys/master/screenrc"
    os.system("wget -O .screenrc -N " +myScreenrc)

def usage():
    print "initsys <machineToInit> <githubUser>"

if __name__ == "__main__":
    if len(sys.argv) < 2 :
        usage()
    elif sys.argv[1] == "remote":
        dlLocalAlias()
        dlLocalVimrc()
        dlLocalScreenrc()
    else :
        print "Let's enable Faeriol's config on this machine: " +sys.argv[1] +" with github user: " +sys.argv[2] 
        copyKey(sys.argv[1], sys.argv[2])
        dlInitsys(sys.argv[1])
        os.system("ssh " +sys.argv[1] +" python ./initsys remote")
        print "DONE"
